export type Juego = {
  nombre: string;
  objetivo: string;
  como: string;
  minutos: number;
  espacio: "Interior" | "Exterior" | "Ambos";
  energia: "Baja" | "Media" | "Alta";
  etapa: "Cachorro" | "Adulto" | "Todas";
  foco: "Olfato" | "Autocontrol" | "Mente" | "Confianza" | "Vínculo";
};

export const JUEGOS: Juego[] = [
  {
    nombre: "Alfombra de olfateo",
    objetivo: "Bajar revoluciones y cansar mentalmente en poco espacio.",
    como: "Esparce su ración diaria entre una manta arrugada o toallas enrolladas y déjalo buscar sin ayuda. Termina cuando encuentre el último trozo.",
    minutos: 10,
    espacio: "Interior",
    energia: "Baja",
    etapa: "Todas",
    foco: "Olfato",
  },
  {
    nombre: "Busca el premio (habitación)",
    objetivo: "Estimulación mental intensa en días de lluvia.",
    como: "Con él fuera, esconde 5 premios a distintas alturas. Entra con la señal «busca» y celebra cada hallazgo sin señalar dónde están.",
    minutos: 12,
    espacio: "Interior",
    energia: "Media",
    etapa: "Todas",
    foco: "Olfato",
  },
  {
    nombre: "Espera y suelta",
    objetivo: "Autocontrol antes de la comida y del juego.",
    como: "Sostén el premio a la vista. Solo lo entregas cuando deja de intentar tomarlo y aparta la mirada un segundo. Sube el tiempo de 1 a 5 segundos.",
    minutos: 5,
    espacio: "Ambos",
    energia: "Baja",
    etapa: "Todas",
    foco: "Autocontrol",
  },
  {
    nombre: "Tira y suelta con reglas",
    objetivo: "Descarga física con freno incluido.",
    como: "Juega al tira y afloja 20 segundos, pide «suelta» con un premio a cambio, pausa 3 segundos y reanuda. El juego se reanuda solo si soltó.",
    minutos: 10,
    espacio: "Ambos",
    energia: "Alta",
    etapa: "Adulto",
    foco: "Autocontrol",
  },
  {
    nombre: "Caja de cartón sorpresa",
    objetivo: "Resolución de problemas y confianza.",
    como: "Mete premios entre papeles arrugados dentro de una caja. Que la resuelva solo; no ayudes salvo que se frustre más de un minuto.",
    minutos: 10,
    espacio: "Interior",
    energia: "Media",
    etapa: "Todas",
    foco: "Mente",
  },
  {
    nombre: "Vasos invertidos",
    objetivo: "Concentración y memoria corta.",
    como: "Tres vasos, un premio bajo uno. Deja que lo vea, mueve lentamente y permítele elegir con la nariz. Acierte o no, repite tres rondas.",
    minutos: 8,
    espacio: "Interior",
    energia: "Baja",
    etapa: "Todas",
    foco: "Mente",
  },
  {
    nombre: "Circuito casero de obstáculos",
    objetivo: "Coordinación y gasto físico controlado.",
    como: "Sillas, cojines y una escoba a baja altura. Guíalo con comida en la mano, siempre despacio y sobre superficie no resbalosa.",
    minutos: 15,
    espacio: "Ambos",
    energia: "Alta",
    etapa: "Adulto",
    foco: "Confianza",
  },
  {
    nombre: "Nombre de los juguetes",
    objetivo: "Vocabulario y foco en ti.",
    como: "Repite el nombre de un juguete cada vez que lo toma. Tras 20 repeticiones, pídeselo entre dos objetos y premia el acierto.",
    minutos: 10,
    espacio: "Interior",
    energia: "Baja",
    etapa: "Todas",
    foco: "Mente",
  },
  {
    nombre: "Escondite humano",
    objetivo: "Reforzar que venir a ti siempre vale la pena.",
    como: "Alguien lo sujeta, tú te escondes y lo llamas una sola vez. Cuando te encuentra, fiesta grande de 5 segundos.",
    minutos: 10,
    espacio: "Ambos",
    energia: "Media",
    etapa: "Todas",
    foco: "Vínculo",
  },
  {
    nombre: "Superficies nuevas",
    objetivo: "Confianza en cachorros y perros miedosos.",
    como: "Coloca 3 texturas (alfombra, plástico, madera). Premia por pisar voluntariamente. Nunca lo arrastres ni lo empujes.",
    minutos: 8,
    espacio: "Interior",
    energia: "Baja",
    etapa: "Cachorro",
    foco: "Confianza",
  },
  {
    nombre: "Masticación programada",
    objetivo: "Calma profunda antes de quedarse solo.",
    como: "Kong congelado o mordedor natural 20 minutos antes de tu salida. La masticación baja el pulso y anticipa descanso.",
    minutos: 20,
    espacio: "Interior",
    energia: "Baja",
    etapa: "Todas",
    foco: "Autocontrol",
  },
  {
    nombre: "Paseo de olfateo lento",
    objetivo: "El mejor gasto energético por minuto.",
    como: "20 minutos de correa larga sin destino: él elige dónde huele y cuánto. Tú solo caminas detrás.",
    minutos: 20,
    espacio: "Exterior",
    energia: "Media",
    etapa: "Todas",
    foco: "Olfato",
  },
  {
    nombre: "Sentarse antes de cruzar",
    objetivo: "Autocontrol útil en la vida real.",
    como: "En cada esquina o puerta, pide sentarse y espera 2 segundos antes de avanzar. Avanzar es el premio.",
    minutos: 5,
    espacio: "Exterior",
    energia: "Baja",
    etapa: "Todas",
    foco: "Autocontrol",
  },
  {
    nombre: "Dos premios, dos manos",
    objetivo: "Cambiar el foco cuando algo lo activa.",
    como: "Lanza un premio a la izquierda, cuando vuelva lanza a la derecha. Sirve para desactivar tensión en la calle sin confrontar.",
    minutos: 6,
    espacio: "Exterior",
    energia: "Media",
    etapa: "Adulto",
    foco: "Vínculo",
  },
  {
    nombre: "Rueda de premios en botella",
    objetivo: "Independencia y entretención sin ti.",
    como: "Botella de plástico con agujeros y pienso dentro. Supervisa siempre y retírala si la muerde en trozos.",
    minutos: 12,
    espacio: "Ambos",
    energia: "Media",
    etapa: "Todas",
    foco: "Mente",
  },
  {
    nombre: "Relajación en la manta",
    objetivo: "Enseñar a apagarse, no solo a obedecer.",
    como: "Manta fija, premios uno a uno mientras esté echado, en silencio. Termina antes de que se levante por aburrimiento.",
    minutos: 10,
    espacio: "Interior",
    energia: "Baja",
    etapa: "Todas",
    foco: "Confianza",
  },
];

export const FOCOS = ["Olfato", "Autocontrol", "Mente", "Confianza", "Vínculo"] as const;
