/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BaseRouteImport } from './routes/base'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCalendarioRouteImport } from './routes/app.calendario'
import { Route as AppDiagnosticoRouteImport } from './routes/app.diagnostico'
import { Route as AppJuegosRouteImport } from './routes/app.juegos'
import { Route as AppPlanRouteImport } from './routes/app.plan'
import { Route as AppRecordatoriosRouteImport } from './routes/app.recordatorios'
import { Route as AppRutinaRouteImport } from './routes/app.rutina'
import { Route as AppSenalesRouteImport } from './routes/app.senales'
import { Route as AppSolucionesRouteImport } from './routes/app.soluciones'
import { Route as AppTriajeRouteImport } from './routes/app.triaje'
import { Route as ApiPublicHotmartRouteImport } from './routes/api/public/hotmart'
import { Route as AppAdminDiagnosticoRouteImport } from './routes/app.admin.diagnostico'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseRoute = BaseRouteImport.update({
  id: '/base',
  path: '/base',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarioRoute = AppCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AppRoute,
} as any)
const AppDiagnosticoRoute = AppDiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => AppRoute,
} as any)
const AppJuegosRoute = AppJuegosRouteImport.update({
  id: '/juegos',
  path: '/juegos',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordatoriosRoute = AppRecordatoriosRouteImport.update({
  id: '/recordatorios',
  path: '/recordatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppRutinaRoute = AppRutinaRouteImport.update({
  id: '/rutina',
  path: '/rutina',
  getParentRoute: () => AppRoute,
} as any)
const AppSenalesRoute = AppSenalesRouteImport.update({
  id: '/senales',
  path: '/senales',
  getParentRoute: () => AppRoute,
} as any)
const AppSolucionesRoute = AppSolucionesRouteImport.update({
  id: '/soluciones',
  path: '/soluciones',
  getParentRoute: () => AppRoute,
} as any)
const AppTriajeRoute = AppTriajeRouteImport.update({
  id: '/triaje',
  path: '/triaje',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicHotmartRoute = ApiPublicHotmartRouteImport.update({
  id: '/api/public/hotmart',
  path: '/api/public/hotmart',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminDiagnosticoRoute = AppAdminDiagnosticoRouteImport.update({
  id: '/admin/diagnostico',
  path: '/admin/diagnostico',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/base': typeof BaseRoute
  '/checkout': typeof CheckoutRoute
  '/premium': typeof PremiumRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/diagnostico': typeof AppDiagnosticoRoute
  '/app/juegos': typeof AppJuegosRoute
  '/app/plan': typeof AppPlanRoute
  '/app/recordatorios': typeof AppRecordatoriosRoute
  '/app/rutina': typeof AppRutinaRoute
  '/app/senales': typeof AppSenalesRoute
  '/app/soluciones': typeof AppSolucionesRoute
  '/app/triaje': typeof AppTriajeRoute
  '/app/': typeof AppIndexRoute
  '/api/public/hotmart': typeof ApiPublicHotmartRoute
  '/app/admin/diagnostico': typeof AppAdminDiagnosticoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/base': typeof BaseRoute
  '/checkout': typeof CheckoutRoute
  '/premium': typeof PremiumRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/diagnostico': typeof AppDiagnosticoRoute
  '/app/juegos': typeof AppJuegosRoute
  '/app/plan': typeof AppPlanRoute
  '/app/recordatorios': typeof AppRecordatoriosRoute
  '/app/rutina': typeof AppRutinaRoute
  '/app/senales': typeof AppSenalesRoute
  '/app/soluciones': typeof AppSolucionesRoute
  '/app/triaje': typeof AppTriajeRoute
  '/app': typeof AppIndexRoute
  '/api/public/hotmart': typeof ApiPublicHotmartRoute
  '/app/admin/diagnostico': typeof AppAdminDiagnosticoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/base': typeof BaseRoute
  '/checkout': typeof CheckoutRoute
  '/premium': typeof PremiumRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/diagnostico': typeof AppDiagnosticoRoute
  '/app/juegos': typeof AppJuegosRoute
  '/app/plan': typeof AppPlanRoute
  '/app/recordatorios': typeof AppRecordatoriosRoute
  '/app/rutina': typeof AppRutinaRoute
  '/app/senales': typeof AppSenalesRoute
  '/app/soluciones': typeof AppSolucionesRoute
  '/app/triaje': typeof AppTriajeRoute
  '/app/': typeof AppIndexRoute
  '/api/public/hotmart': typeof ApiPublicHotmartRoute
  '/app/admin/diagnostico': typeof AppAdminDiagnosticoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/base'
    | '/checkout'
    | '/premium'
    | '/app/calendario'
    | '/app/diagnostico'
    | '/app/juegos'
    | '/app/plan'
    | '/app/recordatorios'
    | '/app/rutina'
    | '/app/senales'
    | '/app/soluciones'
    | '/app/triaje'
    | '/app/'
    | '/api/public/hotmart'
    | '/app/admin/diagnostico'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/base'
    | '/checkout'
    | '/premium'
    | '/app/calendario'
    | '/app/diagnostico'
    | '/app/juegos'
    | '/app/plan'
    | '/app/recordatorios'
    | '/app/rutina'
    | '/app/senales'
    | '/app/soluciones'
    | '/app/triaje'
    | '/app'
    | '/api/public/hotmart'
    | '/app/admin/diagnostico'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/base'
    | '/checkout'
    | '/premium'
    | '/app/calendario'
    | '/app/diagnostico'
    | '/app/juegos'
    | '/app/plan'
    | '/app/recordatorios'
    | '/app/rutina'
    | '/app/senales'
    | '/app/soluciones'
    | '/app/triaje'
    | '/app/'
    | '/api/public/hotmart'
    | '/app/admin/diagnostico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  BaseRoute: typeof BaseRoute
  CheckoutRoute: typeof CheckoutRoute
  PremiumRoute: typeof PremiumRoute
  ApiPublicHotmartRoute: typeof ApiPublicHotmartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base': {
      id: '/base'
      path: '/base'
      fullPath: '/base'
      preLoaderRoute: typeof BaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendario': {
      id: '/app/calendario'
      path: '/calendario'
      fullPath: '/app/calendario'
      preLoaderRoute: typeof AppCalendarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/diagnostico': {
      id: '/app/diagnostico'
      path: '/diagnostico'
      fullPath: '/app/diagnostico'
      preLoaderRoute: typeof AppDiagnosticoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/juegos': {
      id: '/app/juegos'
      path: '/juegos'
      fullPath: '/app/juegos'
      preLoaderRoute: typeof AppJuegosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plan': {
      id: '/app/plan'
      path: '/plan'
      fullPath: '/app/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recordatorios': {
      id: '/app/recordatorios'
      path: '/recordatorios'
      fullPath: '/app/recordatorios'
      preLoaderRoute: typeof AppRecordatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rutina': {
      id: '/app/rutina'
      path: '/rutina'
      fullPath: '/app/rutina'
      preLoaderRoute: typeof AppRutinaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/senales': {
      id: '/app/senales'
      path: '/senales'
      fullPath: '/app/senales'
      preLoaderRoute: typeof AppSenalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/soluciones': {
      id: '/app/soluciones'
      path: '/soluciones'
      fullPath: '/app/soluciones'
      preLoaderRoute: typeof AppSolucionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/triaje': {
      id: '/app/triaje'
      path: '/triaje'
      fullPath: '/app/triaje'
      preLoaderRoute: typeof AppTriajeRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hotmart': {
      id: '/api/public/hotmart'
      path: '/api/public/hotmart'
      fullPath: '/api/public/hotmart'
      preLoaderRoute: typeof ApiPublicHotmartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/diagnostico': {
      id: '/app/admin/diagnostico'
      path: '/admin/diagnostico'
      fullPath: '/app/admin/diagnostico'
      preLoaderRoute: typeof AppAdminDiagnosticoRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCalendarioRoute: typeof AppCalendarioRoute
  AppDiagnosticoRoute: typeof AppDiagnosticoRoute
  AppJuegosRoute: typeof AppJuegosRoute
  AppPlanRoute: typeof AppPlanRoute
  AppRecordatoriosRoute: typeof AppRecordatoriosRoute
  AppRutinaRoute: typeof AppRutinaRoute
  AppSenalesRoute: typeof AppSenalesRoute
  AppSolucionesRoute: typeof AppSolucionesRoute
  AppTriajeRoute: typeof AppTriajeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminDiagnosticoRoute: typeof AppAdminDiagnosticoRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarioRoute: AppCalendarioRoute,
  AppDiagnosticoRoute: AppDiagnosticoRoute,
  AppJuegosRoute: AppJuegosRoute,
  AppPlanRoute: AppPlanRoute,
  AppRecordatoriosRoute: AppRecordatoriosRoute,
  AppRutinaRoute: AppRutinaRoute,
  AppSenalesRoute: AppSenalesRoute,
  AppSolucionesRoute: AppSolucionesRoute,
  AppTriajeRoute: AppTriajeRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminDiagnosticoRoute: AppAdminDiagnosticoRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  BaseRoute: BaseRoute,
  CheckoutRoute: CheckoutRoute,
  PremiumRoute: PremiumRoute,
  ApiPublicHotmartRoute: ApiPublicHotmartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
